# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f61923938acc85d20c3378316d6dfb37a6229df67e5c9283eee85766579a39d0186869fbbcf0bbf2bde04a6a86ac209872fe1dc9fe8c6b0b3836d5fcff53af92

test:
  secret_key_base: fc2642a6b02067a325bfdb7c7591bb5e95e897e379494e550f3133f14b7712e27afe2390c5e20111beeb36f2837700bdea555819180ed6ae66f60040ec9ce46c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
